version: '3.9'

services:
  scraper:
    build: .
    container_name: news_scraper
    volumes:
      - ./data:/app/data
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/newsdb
    command: tail -f /dev/null   # Mantener contenedor activo

  db:
    image: postgres:15
    container_name: news_db
    restart: always
    environment:
      POSTGRES_DB: noticias
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
